# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160705_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='code',
            field=models.CharField(default='qqq', max_length=50, verbose_name='\u041a\u043e\u0434 \u0442\u0435\u0433\u0430(\u0434\u043b\u044f \u0444\u0438\u043b\u044c\u0442\u0440\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='img_url',
            field=models.CharField(help_text='blog/img/authors/[file_name].jpg', max_length=190, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='\u0422\u044d\u0433'),
        ),
    ]
