# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439')),
                ('is_publish', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439',
                'verbose_name_plural': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u0442\u0435\u043a\u0441\u0442\u043e\u0432 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439',
            },
        ),
    ]
