# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinwest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioLevel',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='\u041a\u043e\u0434 \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u0442\u0440\u0430(\u0442\u043e\u043b\u044c\u043a\u043e \u043b\u0430\u0442\u0438\u043d\u0441\u043a\u0438\u0435 \u0441\u0438\u043c\u0432\u043e\u043b\u044b)')),
                ('name', models.CharField(max_length=50, verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b \u043f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0437\u0434\u0435\u043b \u043f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e',
                'verbose_name_plural': '\u0440',
            },
        ),
    ]
